branch-defaults:
  whatthehealth:
    environment: what-the-health
environment-defaults:
  what-the-health:
    branch: null
    repository: null
global:
  application_name: october
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/PHP 7.1 running on
    64bit Amazon Linux/2.6.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
